// Generated by CoffeeScript 1.6.3
(function() {
  var berry, body, canvas, ctx, die, dirStep, framewait, gameloop, h, head, newBerry, score, sectionSize, start, stepSize, t0, w;

  w = h = 1000;

  framewait = 30;

  dirStep = 0.1;

  stepSize = 7;

  sectionSize = 4;

  document.body.innerHTML = "<canvas style=\"position:absolute;top:0;left:0;width:100%;height:100%\" id=\"canvas\" width=" + w + " height=" + h + "></canvas>";

  canvas = document.getElementById("canvas");

  ctx = canvas.getContext("2d");

  t0 = Date.now();

  score = 0;

  score = head = body = void 0;

  berry = {
    x: 500,
    y: 500
  };

  newBerry = function() {
    ctx.beginPath();
    ctx.arc(berry.x, berry.y, sectionSize * 4 + 1, 0, Math.PI * 2);
    ctx.fillStyle = "#002";
    ctx.fill();
    ++score;
    berry = {
      x: Math.random() * 800 + 100,
      y: Math.random() * 800 + 100
    };
    ctx.beginPath();
    ctx.arc(berry.x, berry.y, sectionSize * 4, 0, Math.PI * 2);
    ctx.fillStyle = "#0f0";
    return ctx.fill();
  };

  start = function() {
    ctx.fillStyle = "#002";
    ctx.fillRect(0, 0, 1000, 1000);
    ctx.fillStyle = "#fff";
    ctx.fillRect(5, 5, 990, 990);
    ctx.fillStyle = "#002";
    ctx.fillRect(15, 15, 970, 970);
    score = 0;
    newBerry();
    head = {
      x: w / 2,
      y: h / 2,
      dir: 0,
      dirStep: dirStep
    };
    body = [];
    return gameloop();
  };

  die = function() {
    var dieLoop, i;
    i = 0;
    dieLoop = function() {
      if (i > 10) {
        return start();
      }
      ctx.fillStyle = "rgba(0,0,32,0.3)";
      ctx.fillRect(0, 0, 1000, 1000);
      ctx.fillStyle = "rgba(0,255,0,1)";
      ctx.font = "200px sans serif";
      ctx.fillText("" + (score - 1) + "•", 300, 500);
      console.log("here", i);
      ++i;
      return setTimeout(dieLoop, 300);
    };
    return setTimeout(dieLoop, 1000);
  };

  gameloop = function() {
    var p, startTime, tail;
    startTime = Date.now();
    body.push({
      x: head.x,
      y: head.y
    });
    head.x += Math.sin(head.dir) * stepSize;
    head.y += Math.cos(head.dir) * stepSize;
    head.dir += head.dirStep;
    p = ctx.getImageData(head.x, head.y, 1, 1).data;
    if (p[0]) {
      return die();
    } else if (p[1]) {
      newBerry();
    }
    ctx.beginPath();
    ctx.arc(head.x, head.y, sectionSize, 0, Math.PI * 2);
    ctx.fillStyle = "#f00";
    ctx.fill();
    if (body.length > score * 30) {
      tail = body.shift();
      ctx.beginPath();
      ctx.arc(tail.x, tail.y, sectionSize + 2, 0, Math.PI * 2);
      ctx.fillStyle = "rgba(0,0,0,1)";
      ctx.fill();
    }
    return setTimeout(gameloop, Math.max(0, framewait - (Date.now() - startTime)));
  };

  start();

  document.body.onkeydown = document.body.onmousedown = document.body.ontouchstart = function() {
    head.dirStep *= -1;
    return true;
  };

}).call(this);
